### PR TITLE
Fixed photon check

### LINKED ISSUE #369: DBR 12.2 LTS not supported by Mosaic 0.3.10 ?
The latest release of mosaic (0.3.10) is warning that my Databricks runtime is not supported (12.2 LTS). I think that this is probably an error/bug?

image

image

### PR DESCRIPTION
**Pull request by edurdevic**
This fixes #369

### CODE REVIEW

File: src/main/scala/com/databricks/labs/mosaic/functions/MosaicContext.scala [hunk 1]
```diff
@@ -939,7 +939,12 @@ object MosaicContext extends Logging {
     def checkDBR(spark: SparkSession): Boolean = {
         val sparkVersion = spark.conf.get("spark.databricks.clusterUsageTags.sparkVersion", "")
         val isML = sparkVersion.contains("-ml-")
-        val isPhoton = spark.conf.get("spark.databricks.photon.enabled", "false").toBoolean
+        var isPhoton = false
+        try {
```
Comment (milos-colic) [inline src/main/scala/com/databricks/labs/mosaic/functions/MosaicContext.scala:943]: @edurdevic can we replace this try block with `getOption` call:
`spark.conf.getOption("spark.databricks.photon.enabled").getOrElse("false").toBoolean`

**Review by milos-colic — CHANGES_REQUESTED** [review]

**Review by milos-colic — APPROVED** [review]
LGTM
